Repository open-rpc/client-js, pull requests merged in 2019-07, with the labels that each got.

#46 fix: move semantic deps to circle
  .circleci/config.yml
  package-lock.json
  package.json
Labels: bug

#48 fix: deterministic id and cleanup
  src/RequestManager.test.ts
  src/RequestManager.ts
Labels: bug, enhancement

#52 fix: event emitter transport
  src/RequestManager.test.ts
  src/RequestManager.ts
  src/index.test.ts
  src/transports/EventEmitterTransport.test.ts
  src/transports/EventEmitterTransport.ts
Labels: bug

#50 fix: refactor request manager connect
  src/RequestManager.ts
Labels: enhancement

#51 fix: mocking
  src/RequestManager.test.ts
  src/RequestManager.ts
  src/transports/EventEmitterTransport.ts
Labels: bug, enhancement

#47 feat: batching
  src/RequestManager.test.ts
  src/RequestManager.ts
  src/index.test.ts
  src/index.ts
  src/transports/EventEmitterTransport.test.ts
  src/transports/EventEmitterTransport.ts
Labels: bug
